Fix line causing an error in typescript 2.7.2
Seen in a typescript project using avsc:

```
node_modules/avsc/types/index.d.ts(72,3): error TS7010: '_skip', which
lacks return-type annotation, implicitly has an 'any' return type.
```